version: '3.8'

services:
  web:
    build: .
    container_name: penpal_web_prod
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - media_files:/app/penpal/media
      - static_files:/app/penpal/staticfiles
      - db_data:/app/penpal/db
    restart: always
    command: sh -c "python manage.py collectstatic --noinput && python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  media_files:
  static_files:
  db_data:

