# Generated by Django 5.2.7 on 2025-10-27 09:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Document title', max_length=200)),
                ('content', models.TextField(help_text='HTML content for TipTap editor')),
                ('block_note_content', models.JSONField(default=list, help_text='BlockNote structured content')),
                ('description', models.TextField(blank=True, help_text='Document description/summary')),
                ('document_type', models.CharField(choices=[('blog', 'Blog Post'), ('tutorial', 'Tutorial'), ('tech-doc', 'Technical Documentation'), ('marketing', 'Marketing Content')], default='blog', max_length=50)),
                ('editor_type', models.CharField(choices=[('tiptap', 'TipTap'), ('blocknote', 'BlockNote'), ('hybrid', 'Hybrid')], default='hybrid', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('read_time', models.CharField(blank=True, help_text='Estimated read time', max_length=20)),
                ('tags', models.JSONField(default=list, help_text='Document tags')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['author', 'status'], name='document_do_author__8dd718_idx'), models.Index(fields=['document_type', 'status'], name='document_do_documen_033625_idx'), models.Index(fields=['editor_type'], name='document_do_editor__5b990b_idx'), models.Index(fields=['created_at'], name='document_do_created_778a6d_idx')],
            },
        ),
    ]
